# Generated by Django 4.0.3 on 2022-06-10 21:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_no', models.IntegerField(null=True)),
                ('class_title', models.CharField(max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Classes',
            },
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_name', models.CharField(max_length=255, null=True)),
                ('address', models.CharField(max_length=255, null=True)),
                ('contact', models.IntegerField(null=True)),
                ('cnic', models.IntegerField(null=True)),
                ('email', models.EmailField(max_length=60, null=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('contact', models.IntegerField(null=True)),
                ('address', models.CharField(max_length=255, null=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Upcoming_Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50, null=True)),
                ('date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('roll_number', models.IntegerField(null=True)),
                ('gender', models.CharField(max_length=10, null=True)),
                ('dob', models.DateField(null=True)),
                ('age', models.IntegerField(null=True)),
                ('father_cnic', models.IntegerField(null=True)),
                ('attendence', models.CharField(max_length=25, null=True)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.parent')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.school')),
                ('student_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.class')),
            ],
        ),
        migrations.CreateModel(
            name='Result_Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urdu_obtained', models.IntegerField(null=True)),
                ('urdu_total', models.IntegerField(null=True)),
                ('english_obtained', models.IntegerField(null=True)),
                ('english_total', models.IntegerField(null=True)),
                ('maths_obtained', models.IntegerField(null=True)),
                ('maths_total', models.IntegerField(null=True)),
                ('physics_obtained', models.IntegerField(null=True)),
                ('physics_total', models.IntegerField(null=True)),
                ('chemistry_obtained', models.IntegerField(null=True)),
                ('chemistry_total', models.IntegerField(null=True)),
                ('bio_obtained', models.IntegerField(null=True)),
                ('bio_total', models.IntegerField(null=True)),
                ('computer_obtained', models.IntegerField(null=True)),
                ('computer_total', models.IntegerField(null=True)),
                ('pakstudies_obtained', models.IntegerField(null=True)),
                ('pakstudies_total', models.IntegerField(null=True)),
                ('islamiyat_obtained', models.IntegerField(null=True)),
                ('islamiyat_total', models.IntegerField(null=True)),
                ('science_obtained', models.IntegerField(null=True)),
                ('science_total', models.IntegerField(null=True)),
                ('arabic_obtained', models.IntegerField(null=True)),
                ('arabic_total', models.IntegerField(null=True)),
                ('total_obtained', models.IntegerField(null=True)),
                ('total_marks', models.IntegerField(null=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.student')),
            ],
        ),
        migrations.AddField(
            model_name='parent',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.school'),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, null=True)),
                ('description', models.TextField(null=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.school')),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.school'),
        ),
        migrations.CreateModel(
            name='Attendence_Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Monday', models.CharField(max_length=10, null=True)),
                ('Tuesday', models.CharField(max_length=10, null=True)),
                ('Wednesday', models.CharField(max_length=10, null=True)),
                ('Thursday', models.CharField(max_length=10, null=True)),
                ('Friday', models.CharField(max_length=10, null=True)),
                ('Saturday', models.CharField(max_length=10, null=True)),
                ('Date', models.DateField(auto_now_add=True, null=True)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.student')),
            ],
        ),
    ]
