# Generated by Django 4.0.4 on 2022-06-13 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_student_attendence_alter_parent_cnic'),
    ]

    operations = [
        migrations.AddField(
            model_name='upcoming_test',
            name='description',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='upcoming_test',
            name='for_class',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='upcoming_test',
            name='test_class',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dashboard.class'),
        ),
    ]
