# Generated by Django 4.0.4 on 2022-06-13 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_upcoming_test_description_upcoming_test_for_class_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upcoming_test',
            name='test_class',
        ),
        migrations.AlterField(
            model_name='upcoming_test',
            name='for_class',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dashboard.class'),
        ),
    ]
